# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: audio_streaming.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'audio_streaming.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x61udio_streaming.proto\"0\n\x0c\x41udioRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x12\n\naudio_path\x18\x02 \x01(\t\"O\n\nAudioChunk\x12\x12\n\naudio_data\x18\x01 \x01(\x0c\x12\x16\n\x0e\x63hunk_sequence\x18\x02 \x01(\x05\x12\x15\n\ris_last_chunk\x18\x03 \x01(\x08\x32>\n\x0c\x41udioService\x12.\n\x0eGetAudioStream\x12\r.AudioRequest\x1a\x0b.AudioChunk0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'audio_streaming_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AUDIOREQUEST']._serialized_start=25
  _globals['_AUDIOREQUEST']._serialized_end=73
  _globals['_AUDIOCHUNK']._serialized_start=75
  _globals['_AUDIOCHUNK']._serialized_end=154
  _globals['_AUDIOSERVICE']._serialized_start=156
  _globals['_AUDIOSERVICE']._serialized_end=218
# @@protoc_insertion_point(module_scope)
